local _, CritterEmote = ...
if GetLocale() == "ptBR" then
CritterEmote.General_emotes = {
	name="Geral",
	"faz uma pequena dança.",
	"faz uma pequena dança.",
	"está animado(a) para ver novos lugares.",
	"olha ao redor para todas as pessoas.",
	"senta-se no chão.",
	"lê um livro muito bom.",
	"tira algumas fotos.",
	"quer saber quando é a hora do jantar.",
	"acha que você tem um cabelo muito bonito.",
	"entra na batalha.",
	"parece fofo(a).",
	"parece fofo(a).",
	"parece fofo(a).",
	"toma um gole longo.",
	"toma uma xícara de chá.",
	"toma uma xícara de chá.",
	"planta um jardim.",
	"dança um jig.",
	"perde o controle.",
	"canta.",
	"canta.",
	"canta.",
	"canta.",
	"canta.",
	"canta.",
	"canta.",
	"pensa que tudo o que você precisa é amor.",
	"pisca os olhos.",
	"pisca os olhos.",
	"pisca os olhos.",
	"pisca os olhos.",
	"vai te acompanhar.",
	"te ama.",
	"te ama.",
	"te ama.",
	"te adora.",
	"te adora.",
	"te admira.",
	"te admira.",
	"pisca.",
	"pisca.",
	"pisca.",
	"esconde seu saque.",
	"acha o Lich Rei assustador.",
	"acha que Sargeras deveria voltar a ser altruísta.",
	"quer sair em uma aventura.",
	"canta suavemente.",
	"ri.",
	"quer sair em uma aventura.",
	"está cansado(a).",
	"precisa de uma soneca.",
	"gostaria de fazer uma pausa.",
	"quer ir minerar.",
	"gostaria de tentar esfolamento.",
	"gostaria de tentar arqueologia.",
	"gostaria de tentar inscrição.",
	"quer aprender sobre a história dos trolls.",
	"ama arqueologia.",
	"ama o Festival da Vela de Inverno.",
	"ama a Festa da Cerveja.",
	"quer uma bebida.",
	"acena para todos.",
	"fica confuso(a) com sua roupa.",
	"brinca com uma pequena bola.",
	"pensa sobre o significado da vida.",
	"se interessa pelo número 23.",
	"guincha.",
	"sonha acordado(a).",
	"gostaria de ser alimentado(a).",
	"gostaria de ser alimentado(a).",
	"sonha em ser um(a) aventureiro(a).",
	"sonha em lutar contra o Lich Rei.",
	"sonha em lutar contra os Sha.",
	"sonha em lutar contra a Horda de Ferro.",
	"sonha em lutar contra a Legião.",
	"sonha em lutar contra Sargeras.",
	"sonha em lutar contra Asa Negra.",
	"sonha em ser um(a) modelo.",
	"sonha em ser um(a) bombeiro(a).",
	"sonha em ser uma estrela do rock.",
	"sonha com pequenas nuvens cor-de-rosa fofinhas.",
	"sonha em governar Azeroth.",
	"ama a cor verde.",
	"ama a cor roxa.",
	"levanta-se e acena.",
	"quer um copo de água.",
	"senta-se confortavelmente.",
	"cospe no chão.",
	"se enrosca com um bom livro.",
	"precisa de um bom terapeuta depois da última aventura.",
	"olha ao redor com admiração.",
	"olha ao redor com medo.",
	"olha ao redor.",
	"olha ao redor com confusão.",
	"está confuso(a) com a situação atual.",
	"gostaria de um biscoito.",
	"gostaria de um pedaço de bolo.",
	"gostaria de um pouco de leite.",
	"gostaria de um pouco de sorvete.",
	"entende que não há ossos nesse sorvete.",
	"quer brincar na casa de leilões.",
	"quer brincar no banco.",
	"quer visitar um transmogrificador para mudar o visual.",
	"não suporta ficar esperando.",
	"ama torta de abóbora.",
	"não vê a hora do próximo torneio de pesca.",
	"adoraria pescar.",
	"adoraria cozinhar.",
	"sonha com terras distantes.",
	"acha que todos somos parte da matriz.",
	"acha que todos somos parte da matriz.",
	"quer empinar uma pipa.",
	"come alguma coisa.",
	"prepara uma Festa Selvagem, para 1.",
	"prepara uma Festa Generosa, para 1.",
	"prepara uma festa só para si mesmo(a).",
	"se pergunta por que estamos aqui.",
	"gosta do espaço ondulado, não do linear.",
	"gosta do espaço linear, não do ondulado.",
	"se pergunta se você é real.",
	"chora.",
	"te ama!",
	"ama todo mundo!",
	"odeia este lugar.",
	"ama este lugar.",
	"quer se banhar na glória de Onyxia.",
	"quer um biscoito de pet.",
	"ama todos os bichinhos!",
	"sobe nos seus ombros.",
	"persegue um inseto.",
	"pinta.",
	"traça uma linha na areia.",
	"se pergunta por que o Gronn foi rebaixado de Matador de Dragões para Capitão Gancho.",
	"quer crescer e se tornar um dragão.",
	"pensa, logo existe.",
	"ama queijo.",
	"quer encontrar o verdadeiro amor.",
}
end