local _, CritterEmote = ...
if GetLocale() == "frFR" then
CritterEmote.General_emotes = {
	name="Général",
	"fait une petite danse.",
	"fait une petite danse.",
	"est excité(e) de voir de nouveaux endroits.",
	"regarde autour de lui/elle toutes les personnes.",
	"s'assoit par terre.",
	"lit un très bon livre.",
	"prend des photos.",
	"veut savoir quand c'est l'heure du dîner.",
	"pense que vous avez de très beaux cheveux.",
	"charge dans la bataille.",
	"a l'air mignon/mignonne.",
	"a l'air mignon/mignonne.",
	"a l'air mignon/mignonne.",
	"boit une longue gorgée.",
	"prend une tasse de thé.",
	"prend une tasse de thé.",
	"plante un jardin.",
	"fait une gigue.",
	"perd la tête.",
	"chante.",
	"chante.",
	"chante.",
	"chante.",
	"chante.",
	"chante.",
	"chante.",
	"pense que tout ce dont on a besoin, c'est l'amour.",
	"cligne des yeux.",
	"cligne des yeux.",
	"cligne des yeux.",
	"cligne des yeux.",
	"vous accompagnera.",
	"vous aime.",
	"vous aime.",
	"vous aime.",
	"vous adore.",
	"vous adore.",
	"vous admire.",
	"vous admire.",
	"fait un clin d'œil.",
	"fait un clin d'œil.",
	"fait un clin d'œil.",
	"cache son butin.",
	"pense que le Roi-Liche est effrayant.",
	"pense que Sargeras devrait redevenir altruiste.",
	"veut partir à l'aventure.",
	"couve des yeux.",
	"glousse.",
	"veut partir à l'aventure.",
	"est fatigué(e).",
	"a besoin d'une sieste.",
	"aimerait faire une pause.",
	"veut aller miner.",
	"aimerait essayer le dépeçage.",
	"aimerait essayer l'archéologie.",
	"aimerait essayer l'inscription.",
	"veut en apprendre plus sur l'histoire des trolls.",
	"aime l'archéologie.",
	"aime la Fête du Voile d'hiver.",
	"aime la Fête des Brasseurs.",
	"veut une boisson.",
	"salue tout le monde.",
	"s'interroge sur votre tenue.",
	"joue avec une petite balle.",
	"pense au sens de la vie.",
	"s'intéresse au nombre 23.",
	"couine.",
	"rêvasse.",
	"aimerait être nourri(e).",
	"aimerait être nourri(e).",
	"rêve d'être un aventurier.",
	"rêve de combattre le Roi-Liche.",
	"rêve de combattre les Sha.",
	"rêve de combattre la Horde de Fer.",
	"rêve de combattre la Légion.",
	"rêve de combattre Sargeras.",
	"rêve de combattre Aile-de-Sombre.",
	"rêve de devenir mannequin.",
	"rêve de devenir pompier.",
	"rêve de devenir rock star.",
	"rêve de petits nuages roses et duveteux.",
	"rêve de gouverner Azeroth.",
	"aime la couleur verte.",
	"aime la couleur violette.",
	"se lève et salue.",
	"veut un verre d'eau.",
	"s'assoit confortablement.",
	"crache par terre.",
	"se blottit avec un bon livre.",
	"a besoin d'un bon thérapeute après la dernière aventure.",
	"regarde autour de lui/elle avec admiration.",
	"regarde autour de lui/elle avec peur.",
	"regarde autour de lui/elle.",
	"regarde autour de lui/elle avec confusion.",
	"est confus(e) par la situation actuelle.",
	"aimerait un biscuit.",
	"aimerait un morceau de gâteau.",
	"aimerait du lait.",
	"aimerait de la crème glacée.",
	"comprend qu'il n'y a pas d'os dans cette crème glacée.",
	"veut aller jouer à la maison des enchères.",
	"veut aller jouer à la banque.",
	"veut visiter un transmogrificateur pour changer.",
	"ne supporte pas d'attendre.",
	"aime la tarte à la citrouille.",
	"ne peut pas attendre le prochain tournoi de pêche.",
	"adorerait aller pêcher.",
	"adorerait cuisiner.",
	"rêve de terres lointaines.",
	"pense que nous faisons tous partie de la matrice.",
	"pense que nous faisons tous partie de la matrice.",
	"veut faire voler un cerf-volant.",
	"mange de la nourriture.",
	"prépare un festin sauvage pour une personne.",
	"prépare un festin copieux pour une personne.",
	"prépare un festin juste pour lui/elle.",
	"se demande pourquoi nous sommes ici.",
	"aime l'espace bouclé et non pas filandreux.",
	"aime l'espace filandreux et non pas bouclé.",
	"se demande si vous êtes réel(le).",
	"pleure.",
	"vous aime !",
	"aime tout le monde !",
	"déteste cet endroit.",
	"aime cet endroit.",
	"veut se prélasser dans la gloire d'Onyxia.",
	"veut un biscuit pour animal de compagnie.",
	"aime toutes les créatures !",
	"grimpe sur vos épaules.",
	"poursuit un insecte.",
	"peint.",
	"trace une ligne dans le sable.",
	"se demande pourquoi Gronn a été rétrogradé de tueur de dragons à Capitaine Crochet.",
	"veut devenir un dragon en grandissant.",
	"pense, donc est.",
	"ama il formaggio.",
	"veut trouver le véritable amour.",
}
end