local _, CritterEmote = ...
if GetLocale() == "esMX" then
CritterEmote.General_emotes = {
	"hace un pequeño baile.",
	"hace un pequeño baile.",
	"está emocionado de ver nuevos lugares.",
	"mira a todas las personas.",
	"se sienta en el suelo.",
	"lee un muy buen libro.",
	"toma algunas fotos.",
	"quiere saber cuándo es la hora de la cena.",
	"cree que tienes un cabello muy bonito.",
	"se lanza a la batalla.",
	"se ve lindo.",
	"se ve lindo.",
	"se ve lindo.",
	"toma un largo trago.",
	"toma una taza de té.",
	"toma una taza de té.",
	"planta un jardín.",
	"baila una jota.",
	"pierde la razón.",
	"canta.",
	"canta.",
	"canta.",
	"canta.",
	"canta.",
	"canta.",
	"canta.",
	"cree que todo lo que necesitas es amor.",
	"parpadea.",
	"parpadea.",
	"parpadea.",
	"parpadea.",
	"te acompañará.",
	"te ama.",
	"te ama.",
	"te ama.",
	"te adora.",
	"te adora.",
	"te admira.",
	"te admira.",
	"guiña un ojo.",
	"guiña un ojo.",
	"guiña un ojo.",
	"esconde su botín.",
	"cree que el Rey Exánime da miedo.",
	"cree que Sargeras debería volver a ser altruista.",
	"quiere ir de aventura.",
	"arrulla.",
	"se ríe.",
	"quiere ir de aventuras.",
	"está cansado.",
	"necesita una siesta.",
	"quisiera tomar un descanso.",
	"quiere ir a minar.",
	"quisiera probar desuello.",
	"quisiera probar arqueología.",
	"quisiera probar inscripción.",
	"quiere aprender sobre la historia de los trols.",
	"ama la arqueología.",
	"quiere una bebida.",
	"saluda a todos.",
	"se pregunta sobre tu atuendo.",
	"juega con una pequeña pelota.",
	"piensa en el significado de la vida.",
	"le interesa el número 23.",
	"chilla.",
	"se queda en las nubes.",
	"quisiera ser alimentado.",
	"quisiera ser alimentado.",
	"sueña con ser un aventurero.",
	"sueña con luchar contra el Rey Exánime.",
	"sueña con luchar contra los Sha.",
	"sueña con luchar contra la Horda de Hierro.",
	"sueña con luchar contra la Legión.",
	"sueña con luchar contra Sargeras.",
	"sueña con luchar contra Alamuerte.",
	"sueña con ser un modelo de moda.",
	"sueña con ser bombero.",
	"sueña con ser una estrella de rock.",
	"sueña con pequeñas nubes rosas esponjosas.",
	"sueña con gobernar Azeroth.",
	"ama el color verde.",
	"ama el color púrpura.",
	"se levanta y saluda.",
	"quiere un vaso de agua.",
	"se sienta cómodamente.",
	"escupe en el suelo.",
	"se acurruca con un buen libro.",
	"necesita un buen terapeuta después de la última aventura.",
	"mira alrededor con asombro.",
	"mira alrededor con miedo.",
	"mira a su alrededor.",
	"mira a su alrededor con confusión.",
	"está confundido por la situación actual.",
	"quiere una galleta.",
	"quiere un pastel.",
	"quiere un poco de leche.",
	"quiere un helado.",
	"entiende que no hay huesos en ese helado.",
	"quiere ir a jugar a la casa de subastas.",
	"quiere ir a jugar al banco.",
	"quiere visitar un transfigurador para cambiar.",
	"no puede soportar esperar.",
	"ama el pastel de calabaza.",
	"no puede esperar para el próximo torneo de pesca.",
	"le encantaría ir a pescar.",
	"le encantaría cocinar.",
	"sueña con tierras lejanas.",
	"cree que todos somos parte de la matriz.",
	"cree que todos somos parte de la matriz.",
	"quiere volar una cometa.",
	"come algo de comida.",
	"prepara un Banquete Salvaje, para 1.",
	"prepara un Banquete Copioso, para 1.",
	"prepara un banquete solo para sí mismo.",
	"se pregunta por qué estamos aquí.",
	"le gusta el espacio en forma de lazo, no de cuerda.",
	"le gusta el espacio en forma de cuerda, no de lazo.",
	"se pregunta si eres real.",
	"llora.",
	"¡te ama!",
	"¡ama a todos!",
	"odia este lugar.",
	"ama este lugar.",
	"quiere disfrutar de la gloria de Onyxia.",
	"quiere una galleta para mascotas.",
	"ama a todas las criaturas pequeñas.",
	"se sube a tus hombros.",
	"persigue un insecto.",
	"pinta.",
	"traza una línea en la arena.",
	"se pregunta por qué Gronn fue degradado de Matadragones a Capitán Garfio.",
	"quiere crecer y ser un dragón.",
	"piensa, luego existe.",
	"ama el queso.",
	"quiere encontrar el amor verdadero.",
}
end