local _, CritterEmote = ...
if GetLocale() == "deDE" then
CritterEmote.General_emotes = {
	name = "Allgemein",
	"summt eine kleine Melodie.",
	"tanzt ein wenig.","tanzt ein wenig.",
	"ist aufgeregt, neue Orte zu sehen.",
	"schaut sich die Leute um.",
	"setzt sich auf den Boden.",
	"liest ein sehr gutes Buch.",
	"macht ein paar Fotos.",
	"möchte wissen, wann es Abendessen gibt.",
	"denkt, dass du schöne Haare hast.",
	"stürmt in die Schlacht.",
	"sieht niedlich aus.","sieht niedlich aus.","sieht niedlich aus.",
	"trinkt einen langen Schluck.",
	"trinkt eine Tasse Tee.","trinkt eine Tasse Tee.",
	"pflanzt einen Garten.",
	"macht einen Freudentanz.",
	"verliert völlig die Fassung.",
	"singt.","singt.","singt.","singt.","singt.","singt.","singt.",
	"denkt, alles was man braucht, ist Liebe.",
	"blinzelt.","blinzelt.","blinzelt.","blinzelt.",
	"möchte mit dir mitkommen.",
	"liebt dich.","liebt dich.","liebt dich.",
	"vergöttert dich.","vergöttert dich.",
	"bewundert dich.","bewundert dich.",
	"zwinkert.","zwinkert.","zwinkert.",
	"versteckt seine Beute.",
	"findet den Lichkönig gruselig.",
	"denkt, Sargeras sollte wieder altruistisch sein.",
	"möchte auf Abenteuer gehen.",
	"gurrt.",
	"kichert.",
	"möchte auf Abenteuer gehen.",
	"ist müde.",
	"braucht ein Nickerchen.",
	"möchte eine Pause machen.",
	"möchte bergbauen.",
	"möchte das Häuten ausprobieren.",
	"möchte Archäologie ausprobieren.",
	"möchte das Inschriftenwesen ausprobieren.",
	"möchte etwas über Trollgeschichte lernen.",
	"liebt Archäologie.",
	"liebt das Winterhauchfest.",
	"liebt das Braufest.",
	"liebt das Schlotternächtefest.",
	"möchte ein Getränk.",
	"winkt allen zu.",
	"grübelt über dein Outfit nach.",
	"spielt mit einem kleinen Ball.",
	"denkt über den Sinn des Lebens nach.",
	"interessiert sich für die Zahl 23.",
	"quiekt.",
	"träumt vor sich hin.",
	"möchte gefüttert werden.","möchte gefüttert werden.",
	"träumt davon, ein Abenteurer zu sein.",
	"träumt davon, gegen den Lichkönig zu kämpfen.",
	"träumt davon, gegen die Sha zu kämpfen.",
	"träumt davon, gegen die Eisenlegion zu kämpfen.",
	"träumt davon, gegen die Legion zu kämpfen.",
	"träumt davon, gegen Sargeras zu kämpfen.",
	"träumt davon, gegen Darkwing zu kämpfen.",
	"träumt davon, ein Model zu sein.",
	"träumt davon, Feuerwehrmann zu sein.",
	"träumt davon, Rockstar zu sein.",
	"träumt von kleinen rosa fluffigen Wolken.",
	"träumt davon, Azeroth zu beherrschen.",
	"liebt die Farbe Grün.",
	"liebt die Farbe Lila.",
	"steht auf und winkt.",
	"möchte ein Glas Wasser.",
	"setzt sich bequem hin.",
	"spuckt auf den Boden.",
	"kuschelt sich mit einem guten Buch ein.",
	"braucht nach dem letzten Abenteuer einen guten Therapeuten.",
	"schaut sich ehrfürchtig um.",
	"schaut sich ängstlich um.",
	"schaut sich um.",
	"schaut sich verwirrt um.",
	"ist über die aktuelle Situation verwirrt.",
	"möchte einen Keks.",
	"möchte etwas Kuchen.",
	"möchte etwas Milch.",
	"möchte etwas Eis.",
	"versteht, dass in diesem Eis keine Knochen sind.",
	"möchte am Auktionshaus spielen.",
	"möchte in der Bank spielen.",
	"möchte einen Transmogrifizierer besuchen, um Abwechslung zu haben.",
	"kann es nicht ausstehen, herumzuwarten.",
	"liebt Kürbiskuchen.",
	"kann das nächste Angelturnier kaum erwarten.",
	"würde gern angeln gehen.",
	"würde gern kochen.",
	"träumt von fernen Ländern.",
	"denkt, wir sind alle Teil der Matrix.","denkt, wir sind alle Teil der Matrix.",
	"möchte einen Drachen steigen lassen.",
	"isst etwas.",
	"bereitet ein Wildes Festmahl für 1 zu.",
	"bereitet ein Herzhaftes Festmahl für 1 zu.",
	"bereitet ein Festmahl nur für sich selbst zu.",
	"fragt sich, warum wir hier sind.",
	"mag Weltraum lustig, nicht faserig.",
	"mag Weltraum faserig, nicht lustig.",
	"fragt sich, ob du echt bist.",
	"weint.",
	"liebt dich!",
	"liebt alle!",
	"hasst diesen Ort.",
	"liebt diesen Ort.",
	"möchte im Glanz von Onyxia baden.",
	"möchte einen Haustierkeks.",
	"liebt Chinchillas!",
	"klettert auf deine Schultern.",
	"jagt einem Käfer nach.",
	"malt.",
	"zieht eine Linie in den Sand.",
	"fragt sich, warum Gronn vom Drachentöter zum Käpt’n Haken degradiert wurde.",
	"möchte aufwachsen und ein Drache werden.",
	"denkt, also ist er.",
	"liebt Käse.",
	"möchte die wahre Liebe finden.",
	"stellt den Kopf auf, um dem Gespräch zu lauschen, um über die Welt informiert zu bleiben.",
}
end