local _, CritterEmote = ...
if GetLocale() == "itIT" then
CritterEmote.General_emotes = {
	name="Generale",
	"fa un piccolo ballo.",
	"fa un piccolo ballo.",
	"è entusiasta di vedere nuovi posti.",
	"guarda tutte le persone intorno a sé.",
	"si siede per terra.",
	"legge un ottimo libro.",
	"scatta alcune foto.",
	"vuole sapere quando è l'ora di cena.",
	"pensa che hai dei capelli molto belli.",
	"si lancia in battaglia.",
	"sembra carino/carina.",
	"sembra carino/carina.",
	"sembra carino/carina.",
	"beve un lungo sorso.",
	"prende una tazza di tè.",
	"prende una tazza di tè.",
	"pianta un giardino.",
	"fa un ballo tradizionale.",
	"perde il controllo.",
	"canta.",
	"canta.",
	"canta.",
	"canta.",
	"canta.",
	"canta.",
	"canta.",
	"pensa che tutto ciò di cui hai bisogno è amore.",
	"batte le palpebre.",
	"batte le palpebre.",
	"batte le palpebre.",
	"batte le palpebre.",
	"ti seguirà.",
	"ti ama.",
	"ti ama.",
	"ti ama.",
	"ti adora.",
	"ti adora.",
	"ti ammira.",
	"ti ammira.",
	"fa l'occhiolino.",
	"fa l'occhiolino.",
	"fa l'occhiolino.",
	"nasconde il suo bottino.",
	"pensa che il Re dei Lich sia spaventoso.",
	"pensa che Sargeras dovrebbe tornare a essere altruista.",
	"vuole andare all'avventura.",
	"fa il verso.",
	"ride.",
	"vuole andare all'avventura.",
	"è stanco/stanca.",
	"ha bisogno di un pisolino.",
	"vorrebbe fare una pausa.",
	"vuole andare a minare.",
	"vorrebbe provare la scuoiatura.",
	"vorrebbe provare l'archeologia.",
	"vorrebbe provare l'iscrizione.",
	"vuole imparare la storia dei troll.",
	"ama l'archeologia.",
	"ama la Festa del Velo Invernale.",
	"ama la Festa della Birra.",
	"vuole una bevanda.",
	"saluta tutti.",
	"riflette sul tuo abbigliamento.",
	"gioca con una piccola palla.",
	"pensa al senso della vita.",
	"è interessato al numero 23.",
	"strilla.",
	"fantastica.",
	"vorrebbe essere nutrito/nutrita.",
	"vorrebbe essere nutrito/nutrita.",
	"sogna di essere un avventuriero.",
	"sogna di combattere il Re dei Lich.",
	"sogna di combattere gli Sha.",
	"sogna di combattere l'Orda di Ferro.",
	"sogna di combattere la Legione.",
	"sogna di combattere Sargeras.",
	"sogna di combattere Aladuno.",
	"sogna di diventare una modella.",
	"sogna di diventare un pompiere.",
	"sogna di diventare una rock star.",
	"sogna di soffici nuvole rosa.",
	"sogna di governare Azeroth.",
	"ama il colore verde.",
	"ama il colore viola.",
	"si alza e saluta.",
	"vuole un bicchiere d'acqua.",
	"si siede comodamente.",
	"sputa per terra.",
	"si rannicchia con un buon libro.",
	"ha bisogno di un buon terapeuta dopo l'ultima avventura.",
	"guarda intorno con stupore.",
	"guarda intorno con paura.",
	"guarda intorno.",
	"guarda intorno con confusione.",
	"è confuso/a dalla situazione attuale.",
	"vorrebbe un biscotto.",
	"vorrebbe un po' di torta.",
	"vorrebbe del latte.",
	"vorrebbe del gelato.",
	"capisce che non ci sono ossa in quel gelato.",
	"vuole andare a giocare alla casa d'aste.",
	"vuole andare a giocare in banca.",
	"vuole visitare un trasmogrificatore per un cambiamento.",
	"non sopporta di aspettare.",
	"ama la torta di zucca.",
	"non vede l'ora del prossimo torneo di pesca.",
	"adorerebbe andare a pescare.",
	"adorerebbe cucinare.",
	"sogna terre lontane.",
	"pensa che siamo tutti parte della matrice.",
	"pensa che siamo tutti parte della matrice.",
	"vuole far volare un aquilone.",
	"mangia del cibo.",
	"prepara un Banchetto Selvaggio, per 1.",
	"prepara un Banchetto Sostanzioso, per 1.",
	"prepara un banchetto solo per sé stesso/a.",
	"si chiede perché siamo qui.",
	"gli piace lo spazio circolare, non filiforme.",
	"gli piace lo spazio filiforme, non circolare.",
	"si chiede se sei reale.",
	"piange.",
	"ti ama!",
	"ama tutti!",
	"odia questo posto.",
	"ama questo posto.",
	"vuole crogiolarsi nella gloria di Onyxia.",
	"vuole un biscotto per animali.",
	"ama tutte le creature!",
	"si arrampica sulle tue spalle.",
	"insegue un insetto.",
	"dipinge.",
	"traccia una linea nella sabbia.",
	"si chiede perché Gronn è stato retrocesso da uccisore di draghi a Capitan Uncino.",
	"vuole crescere per diventare un drago.",
	"pensa, quindi è.",
	"ama il formaggio.",
	"vuole trovare il vero amore.",
}
end