local _, CritterEmote = ...
if GetLocale() == "esES" then
CritterEmote.General_emotes = {
	"hace un pequeño baile.", "hace un pequeño baile.",
	"está emocionado de ver nuevos lugares.",
	"mira a todas las personas.",
	"se sienta en el suelo.",
	"lee un libro muy bueno.",
	"toma algunas fotos.",
	"quiere saber cuándo es la hora de la cena.",
	"cree que tienes un cabello muy bonito.",
	"carga hacia la batalla.",
	"se ve lindo.", "se ve lindo.", "se ve lindo.",
	"toma un trago largo.",
	"toma una taza de té.", "toma una taza de té.",
	"planta un jardín.",
	"hace un baile.",
	"se vuelve loco.",
	"canta.", "canta.", "canta.", "canta.", "canta.", "canta.", "canta.",
	"cree que todo lo que necesitas es amor.",
	"parpadea.", "parpadea.", "parpadea.", "parpadea.",
	"te seguirá.",
	"te ama.", "te ama.", "te ama.",
	"te adora.", "te adora.",
	"te admira.", "te admira.",
	"guiña un ojo.", "guiña un ojo.", "guiña un ojo.",
	"esconde su botín.",
	"cree que el Rey Exánime da miedo.",
	"cree que Sargeras debería volver a ser altruista.",
	"quiere irse de aventuras.",
	"gorgojea.",
	"se ríe.",
	"quiere ir de aventuras.",
	"está cansado.",
	"necesita una siesta.",
	"le gustaría tomarse un descanso.",
	"quiere ir a minar.",
	"le gustaría probar el desuello.",
	"le gustaría probar la arqueología.",
	"le gustaría probar la inscripción.",
	"quiere aprender sobre la historia de los trols.",
	"ama la arqueología.",
	"quiere una bebida.",
	"saluda a todos.",
	"se sorprende por tu atuendo.",
	"juega con una pequeña pelota.",
	"piensa en el significado de la vida.",
	"está interesado en el número 23.",
	"chilla.",
	"se queda soñando despierto.",
	"quiere que lo alimenten.", "quiere que lo alimenten.",
	"soña con ser un aventurero.",
	"soña con luchar contra el Rey Exánime.",
	"soña con luchar contra los Sha.",
	"soña con luchar contra la Horda de Hierro.",
	"soña con luchar contra la Legión.",
	"soña con luchar contra Sargeras.",
	"soña con luchar contra Alamuerte.",
	"soña con ser modelo.",
	"soña con ser bombero.",
	"soña con ser una estrella de rock.",
	"soña con nubes rosadas y esponjosas.",
	"soña con gobernar Azeroth.",
	"le encanta el color verde.",
	"le encanta el color morado.",
	"se levanta y saluda.",
	"quiere un vaso de agua.",
	"se sienta cómodamente.",
	"escupe en el suelo.",
	"se acurruca con un buen libro.",
	"necesita un buen terapeuta después de la última aventura.",
	"mira a su alrededor con asombro.",
	"mira a su alrededor con miedo.",
	"mira a su alrededor.",
	"mira a su alrededor con confusión.",
	"está confundido por la situación actual.",
	"le gustaría una galleta.",
	"le gustaría un pastel.",
	"le gustaría un poco de leche.",
	"le gustaría un helado.",
	"entiende que no hay huesos en ese helado.",
	"quiere ir a jugar en la casa de subastas.",
	"quiere ir a jugar en el banco.",
	"quiere visitar al transfigurador para un cambio.",
	"no puede soportar esperar.",
	"le encanta el pastel de calabaza.",
	"no puede esperar para el próximo torneo de pesca.",
	"le encantaría ir a pescar.",
	"le encantaría cocinar.",
	"soña con tierras lejanas.",
	"cree que todos somos parte de la matriz.", "cree que todos somos parte de la matriz.",
	"quiere volar una cometa.",
	"come algo.",
	"prepara un festín salvaje, para uno.",
	"prepara un festín abundante, para uno.",
	"prepara un festín solo para sí mismo.",
	"se pregunta por qué estamos aquí.",
	"prefiere el espacio en forma de bucle, no de cuerda.",
	"prefiere el espacio en forma de cuerda, no de bucle.",
	"se pregunta si eres real.",
	"llora.",
	"te ama!",
	"ama a todos!",
	"odia este lugar.",
	"ama este lugar.",
	"quiere disfrutar de la gloria de Onyxia.",
	"quiere una galleta para mascotas.",
	"ama a todas las criaturas!",
	"se sube a tus hombros.",
	"persigue un insecto.",
	"pinta.",
	"dibuja una línea en la arena.",
	"se pregunta por qué Gronn fue degradado de Asesino de Dragones a Capitán Garfio.",
	"quiere crecer y ser un dragón.",
	"piensa, por lo tanto es.",
	"ama el queso.",
	"quiere encontrar el amor verdadero."
}
end