local _, CritterEmote = ...
if GetLocale() == "enUS" then
CritterEmote.Location_emotes = {
	PickTable = function(self)
		local mapInfo = { name="none", parentMapID = C_Map.GetBestMapForUnit("player") }
		while mapInfo.parentMapID ~= 0 do
			mapInfo = C_Map.GetMapInfo( mapInfo.parentMapID )
			CritterEmote.Log(CritterEmote.Debug, "Location: "..mapInfo.name)
			if self[mapInfo.name] then
				CritterEmote.Log(CritterEmote.Debug, "Found location: "..mapInfo.name)
				return self[mapInfo.name]
			end
		end
		return self
	end,
	["Eastern Kingdoms"] = {
		"wants to visit the hardy dwarves in Dun Morogh and maybe grab a drink at the local tavern.",
		"would like to stroll through the peaceful vineyards of Elwynn Forest, where the air is filled with the scent of fresh grapes.",
		"would like to visit the hauntingly beautiful Tirisfal Glades, where the dead now rule.",
		"would like to frolic in Silverpine Forest, though the wolves might have other plans.",
		"wants to clear the bandits out of Westfall and restore peace to the dusty farmlands.",
		"would like to see the wilds of Stranglethorn, where the jungle never sleeps.",
		"wants to run along the riverside in the peaceful Redridge Mountains.",
		"wants to see the giant spiders lurking in the shadows of Duskwood. From a safe distance, of course.",
		"wants to take a dust bath in the barren, rocky Badlands.",
		"would like to see the dinosaurs rumored to roam the wilds of Hillsbrad Foothills.",
		"would like to see the elementals that roam the ancient hills of the Arathi Highlands.",
		"wants to explore the crumbling remains of the Alterac Mountains, once home to a great human kingdom.",
		"would like to visit the remote Hinterlands, a place where nature rules and the skies are alive with griffons.",
		"would like to see the wilds of Stranglethorn, where the jungle never sleeps.",
		"wants to become a zombie in the Western Plaguelands, though it might not be the best life choice.",
		"wants to bring the Light to the Eastern Plaguelands, where darkness has taken root.",
		"would like to take a mudbath in the Wetlands, though the constant rain makes it dangerous and sloppy.",
		"does not want to visit Searing Gorge, a land of fire and smoke where even the air burns.",
		"wants to explore the charred landscape of the Burning Steppes with special heat resistant gear.",
		"never, ever wants to go to Deadwind Pass. It just sounds smelly and cursed.",
		"would not like to get stuck in a bog in the Swamp of Sorrows, where every step sinks deeper into the mire.",
		"wants to see the Dark Portal in the Blasted Lands, where the very fabric of reality seems to tear at the edges.",
		"wants to explore the grand city of Stormwind, where the streets hum with the bustle of adventurers.",
	},
	["Kalimdor"] = {
		"wants to visit the peaceful Tauren tribes in Mulgore, where the plains stretch endlessly.",
		"would like to visit the mystical Night Elves in Teldrassil, where the great tree towers above all.",
		"wants to frolic along the misty shores of Darkshore, listening to the sound of endlessly crashing waves.",
		"wants to explore the magical ancient forests of Ashenvale.",
		"thinks the Goblins have turned Azshara into an odd, chaotic place filled with strange contraptions.",
		"wants to ride the tugboat in the Northern Barrens, where adventure lies around every corner.",
		"thinks Desolace is aptly named, with its barren landscape and ghostly ruins.",
		"wants to explore the lush jungles of Feralas, where ancient secrets lie hidden beneath the canopy.",
		"wants to see a dinosaur in Un'Goro Crater, where prehistoric beasts still roam freely.",
		"wants to explore the twisted forests of Felwood, where the corruption of demons still lingers.",
		"would dress warmly to explore the icy wilderness of Winterspring, where the snow never melts.",
		"wants to visit druids beneath the moonlight in the tranquil Moonglade.",
		"wants to visit the proud Darkspear Trolls in the Echo Isles, where the sound of the sea is ever-present.",
		"wants to explore the harsh, red rocky landscape of Durotar.",
		"wonders why everything on Bloodmyst Isle is so red.",
		"wants to explore Azuremyst Isle, where everything feels bathed in the calm glow of blue.",
		"wants to explore Dustwallow Marsh, where the fog is thick and the land is full of secrets.",
		"wants to explore the vast deserts of Tanaris, where the sands hide ancient secrets.",
	},
	["Outland"] = {
		"wants to avoid Hellfire Peninsula, where the land is scorched and demons still roam freely.",
		"wants to avoid the murky depths of Zangarmarsh, where the giant mushrooms block out the sun.",
		"loves the tranquility of Terokkar Forest, where the trees whisper ancient secrets.",
		"sings about the beauty of Nagrand, where the skies are endless, and the grass is greener than anywhere else.",
		"finds Blade’s Edge Mountains awe-inspiring and tragic, where even mighty dragons are caught in the jagged peaks.",
		"wants to see if the stories about Netherstorm are true. Does magic crackle in the air and reality bend?",
		"wonders if it’s always dark in Shadowmoon Valley, where the land is cursed, and the stars never shine.",
		"wants to understand the history of the Dark Portal, where Azeroth first encountered the Orcish invasion.",
		"would like to wander through the golden trees of Eversong Woods, where the sun never sets.",
		"wants to explore the shining spires of Silvermoon City, the heart of the Blood Elves' power.",
		"wants to visit the haunted Ghostlands, where the remnants of the Scourge still roam.",
		"wants to earn gold on the Isle of Quel'Danas, where adventurers gather to fight the forces of the Burning Legion.",
		"wants to earn gold on the Isle of Quel'Danas, a favorite spot for hard working adventurers seeking fortune.",
	},
	"wants to explore all of Azeroth.",
	"would like to explore most of the Eastern Kingdoms.",
	"would like to explore all of Kalimdor.",
	"is interested in exploring Outlands.",
	"would like to see the beautiful Pandaria.",
	"wants to explore Northrend.",
	"wants to stay home.",
	"wants to explore all of Azeroth.",
	"would like to visit the Eastern Kingdoms.",
	"would like to go see the Dwarves at Dun Morogh.",
	"would like to see the vineyards in Elwynn Forest.",
	"would like to visit Eversong Woods.",
	"would like to visit Gilneas. Does wolfsbane work on Worgens?",
	"would like to visit Tirisfal Glades.",
	"would like to visit Ghostlands",
	"wishes they could have seen the dam in Loch Modan before Darkwing destroyed it.",
	"would like to frolic in Silverpine Forest.",
	"would like to clear the bandits out of Westfall.",
	"would like to run along the riverside in Redridge Mountains.",
	"would like to see the spiders in Duskwood.",
	"would like to see the dinosaurs in Hillsbrad Foothills.",
	"would like to take a mudbath in the Wetlands.",
	"would like to visit the Alterac Mountains.",
	"would like to see the elementals in Arathi Highlands.",
	"would like to visit The Hinterlands.",
	"would like to see the pirates in Stranglethorn.",
	"would like to become a zombie in Western Plaguelands.",
	"would like to bring the Light to the Eastern Plaguelands.",
	"would like to take a dust bath in the Badlands.",
	"would like to visit Searing Gorge.",
	"would like to visit Burning Steppes.",
	"never, ever wants to go to Deadwind Pass. It just sounds smelly.",
	"would not like to get stuck in a bog in the Swamp of Sorrows.",
	"would like to see the Dark Portal in The Blasted Lands.",
	"would like to see the tunnels in Khaz Modan.",
	"would like to visit the dungeons and raids in Blackrock Mountain.",
	"would like to visit the Opera in Karazhan.",
	"would like to earn gold on the Isle of Quel'Danas",
	"would not like to run into the Twighlight Counsel in Twilight Highlands.",
	"would like to win in Tol Barad and see Baradin Hold.",
	"would like to explore Azuremyst Isle. It sounds very blue.",
	"would like to visit the Trolls in Durotar.",
	"would like to see the Tauren in Mulgore.",
	"would like to visit the Night Elves in Teldrassil.",
	"wonders about all the red on Bloodmyst Isle.",
	"would like to watch the fighting in Darkshore.",
	"thinks the Goblins have made Azshara a very odd place.",
	"would like to ride the tugboat in Northern Barrens.",
	"would like to explore Ashenvale.",
	"misses the Stonetalon Mountains from before the Shattering.",
	"Thinks Desolace is appropriately named.",
	"would like to explore Southern Barrens.",
	"would like to explore Dustwallow Marsh.",
	"would like to explore Feralas.",
	"remembers Thousand Needles before the Shattering and misses the races.",
	"would like to explore Tanaris.",
	"would like to explore Felwood.",
	"would like to see a dinosaur in Un'goro Crater.",
	"would like to take a mudbath in Un'goro Crater.",
	"would like to explore Winterspring.",
	"would like to see the sword hilt in Silithus.",
	"would like to explore Moonglade.",
	"would like to burn Mount Hyjal.",
	"would like to mine in Uldum.",
	"would like to explore Ahn'Qiraj.",
	"would like to see the beautiful Pandaria.",
	"wishes to see the Wandering Isle.",
	"wonders about Draenor and alternate universes.",
	"is afraid of the Broken Isles.",
	"is interested in seeing Outland.",
	"dreams about seeing the Dark Portal.",
	"wants to avoid Hellfire Peninsula.",
	"wants to avoid Zangarmarsh.",
	"loves Terokkar Forest.",
	"sings about Nagrand.",
	"thinks Blade's Edge Mountains are the coolest.",
	"would like to see if the stories about Netherstorm are true.",
	"asks if it really is always dark in Shadowmoon Valley.",
	"needs a coat to visit Borean Tundra.",
	"would like to see the Howling Fjord.",
	"wonders what Dragonblight is like.",
	"wonders what Grizzly Hills is like.",
	"would like to see the trolls of Zul'Drak.",
	"would like to see Sholazar Basin.",
	"would like to see the lightning in Storm Peaks.",
	"wonders how trees grow in Crystalsong Forest.",
	"would like to see Hrothgar's Landing.",
	"thinks Icecrown is a scary place.",
	"needs a coat to visit Wintergrasp.",
	"thinks Karazhan is a very tangled place but loves the Opera.",
	"wonders if they ever found the Lost Isles.",
	"would like to swim and breath underwater and see the cool things in Vashj'ir .",
	"would like to raid Icecrown Citadel.",
	"would like to raid The Firelands.",
	"would like to raid Dragon Soul.",
	"wants to be in the Celestial Tournament.",
	"would like to visit the Magical Menagerie.",
	"misses the Vale of Eternal Blossoms, remembering when it was beautiful and not scarred.",
	"never wants to see the world from Kun-Lai Summit.",
	"thinks Townlong Steppes is scary.",
	"wonders how the Wandering Isle wanders.",
	"would like to frolic in the Jade Forest.",
	"would like to go fishing in the Krasarang Wilds and meet Nat Pagle again.",
	"would like to burn the Dread Wastes to the ground.",
	"would like to dance in the thunder on the Isle of the Thunder King.",
	"thinks the dinosaurs of the Isle of Giants are impressive.",
	"wants to live forever on the Timeless Isle.",
	"wants to soar with the wind in the Valley of the Four Winds.",
	"would like to explore the Veiled Stair and buy something from the Black Market.",
	"thinks that the Tanaan Jungle has lots of cool things to see.",
	"would wear something warm when visiting Frostfire Ridge.",
	"wants to visit the elves of Suramar",
	"wants to hunt with Nat Pagel in Highmountain.",
	"wants to see the dragons of Stormheim.",
	"does not want to meet the Legion in Azsuna.",
	"wants to visit the druids in Val'Sharah.",
	"wonders about Thal'Dranath.",
	"wonders if Argus will ever be rid of the Legion.",
	"thinks that the Nightfallen in Suramar are glorified zombies.",
	"remembers when Zandalar rep was a grind before the Cataclysm.",
	"is amazed by Dazaralor.",
	"is a little frightened by Bwomsandi.",
	"wants to see the Volpera in Vol'dun.",
	"wishes Torga was still alive and wonders if there is a relation to the Shen-zin Su.",
	"wants to visit the Tortolla in Nazmir,",
	"wants to visit all the alleyways in Boralus.",
	"would like to fight with the pirates in Tiragarde Sound.",
	"wonders about the Drust of Drustvar.",
	"wishes Queen Azshara would just stay hidden in Nazjatar. ",
	"loves visiting the mech in Mechagon.",
	"is amazed that we can enter The Shadowlands. ",
	"would like to see The Arbiter in Oribos",
	"finds The Jailer in The Maw distasteful",
	"wonders how the dracthyr were frozen in time.",
	"flies with dragons on the Dragon Isles.",
}
end